### ISSUE TITLE
On Problem 2: Truncation

### ISSUE THREAD

**Issue by fcudhea** [INSP-RH/pifpaf#6]
> sdlog<-sqrt(1.7)
> meanlog<-.05
> 
> plnorm(q=0, meanlog=meanlog, sdlog=sdlog)
[1] 0
> plnorm(q=2.5, meanlog=meanlog, sdlog=sdlog)
[1] 0.7467875
> plnorm(q=5, meanlog=meanlog, sdlog=sdlog)
[1] 0.8841584
> plnorm(q=10, meanlog=meanlog, sdlog=sdlog)
[1] 0.9579749
> plnorm(q=100, meanlog=meanlog, sdlog=sdlog)
[1] 0.9997618
> 
> 
> summary(rlnorm(n=100, meanlog=meanlog, sdlog=sdlog))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0161  0.4143  1.1530  3.3660  3.0470 84.8300 

Sorry for ugly code and output. Above is just showing probably of observing values greater than 2.5, 5, 10, and 100 for log-normal, and summary stats for 100 random draws for distribution used in your example. I'm showing it because I think you can make the case that, assuming the parameters are based on data, and that the researchers are assuming truncated lognormal because they believe the exposure distribution is approximately shaped like a lognormal. that the researchers would not use a cutoff as low as 2.5 or 5. Even 10 is may be low. However, once you increase the cutoff to 10, your PAF will be, for all practical purposes, very close to the "true" PAF for the log-normal. Based on this example, it seems like truncation is likely not huge issue as long as max is picked in a reasonable way that is consistent with the data.

I think the log-normal may not be the best example for illustrating the how sensitive the PAF is to truncation since the the log-normal is fundamentally flawed (as you explain in 2.2.1) when R(X; theta) = exp(theta*X). Might be more interesting/helpful to look at gamma distributions that don't diverge and see how sensitive they are truncation (though I have no idea whether dtruc supports gamma).

**Comment by dalia1992** [comment]
The file I uploaded is redoing the example with different parameters for both log-normal, and gamma. The log-normal (heavy-tailed distribution) has the problem in which the moment generating function didn't exist, that's why we decided to make this example just to show how truncation on a heavy-tailed distribution is not the way to go. We did this, because some people have used log-normal distribution for exposure levels, and one might argue that the integral does exist for the truncated log-normal and keep on using log-normal (truncated) distributions. 

The gamma truncation (with the selected parameters (new ones)) doesn't lead to great numerical differences of PAF between the truncation made at 5, 10, or 100. It does make a difference when truncation is made at 2.5, and as you say one might not choose 2.5 for truncation.  Therefore truncation is not such an issue for this gamma distribution.

So truncating the distribution changes the estimated PAF for heavy-tailed distributions (Cauchy, log-normal, etc. Or for more complicated and weird relative risk function that could make the integral non  existent, but this is unlikely to happen. )
[Truncation.pdf](https://github.com/INSP-RH/pif/files/579013/Truncation.pdf)

**Comment by fcudhea** [comment]
Thank you for this! It's Very helpful, I am very relieved since we are using gamma distribution. I wish I could say I foresaw issues with log-normal. But it was actually dumb luck! 

I understand your rationale for presenting the truncation issue in this way. I probably made similar arguments when talking to Rodrigo about this (that truncation will avoid the problem ) before truly understanding the implications of the diverging integral issue.

**Comment by RodrigoZepeda** [comment]
> Thank you for this! It's Very helpful, I am very relieved since we are using gamma distribution.

The example Dalia appended was a specific example: truncation for that specific gamma with that specific sample seemed not an issue; however: this is no _proof_ that for *any gamma* truncation will not be an issue . 

For the comment: 

> Based on this example, it seems like truncation is likely not huge issue as long as max is picked in a reasonable way that is consistent with the data.

Yup: truncation will not be an issue if, say, you adjust a Gamma, check that the model is reasonable (say Kolmogorov-Smirnoff) and estimate (say Maximum Likelihood) the bounds of the truncation. In that specific case truncation will not be `an issue`. However, most of the times (correct me if I am wrong) I've seen truncation be made arbitrarily as in "I think that a BMI of 40 does not make sense"; another researcher might say "I think that a BMI of 110 does not make sense". Maybe both are right; however, that truncation will affect their results.

**Comment by RodrigoZepeda** [comment]
To me, the morale of the story we are trying to convey is: you can skew your results by choosing your distribution to give you high-PAFs or low-PAFs (consciously or not). Several top-Bayesians have argued against this method saying that the frequentists are right and choosing a distribution "out of nowhere" skews results (and that's the idea of hierarchical methods). As an example consider [Berger](https://projecteuclid.org/download/pdf_1/euclid.ba/1340371035) specifically section 4 where he criticizes:

> choosing priors with tuning parameters that are adjusted until the answer
“looks nice.” I call such analyses pseudo-Bayes because, while they utilize Bayesian
machinery, they do not carry with them any of the guarantees of good performance
that come with either true subjective analysis (with a very extensive elicitation effort)
or (well-studied) objective Bayesian analysis

**Comment by RodrigoZepeda** [comment]
We have produced a proof to show that in the case of strictly increasing Relative Risks (say exponential or linear) one can choose a truncation limit in order to get ANY PAF one wants. This works for both the lognormal and gamma casw we've discussed. I am appending the pdf document here.

[Proof_PAF.pdf](https://github.com/INSP-RH/pif/files/662334/Proof_PAF.pdf)

**Comment by fcudhea** [comment]
> The example Dalia appended was a specific example: truncation for that specific gamma with that specific sample seemed not an issue; however: this is no proof that for any gamma truncation will not be an issue .

I understand. Maybe I failed to add some context. What I was saying is that I'm happy we chose the gamma distribution instead of the log-normal which appears to _always_ give a PAF of 1. 

Thanks for link to paper and your proof. Will look over it more closely when I have the chance. 

I understand that you can manipulate your truncation limit to get whatever PAF you want if the "true" untruncated PAF is 1 (as is the case with the log-normal and certain cases of the gamma, as you've explained) and I understand this empirical method will be much more robust to the whims of researchers than any kind of method that depends on distributional assumptions.  

The point I was trying to make when I started this thread is that I didn't see how truncation is its own issue. Truncation to "counteract" choosing a distribution that guarantees a PAF of 1, will of course be very sensitive to truncation limit. But this seems more like an illustration of why problem 1 is an issue that cannot be "solved" by truncation, not it's own problem. 

That's why I proposed looking at a gamma distribution that does converge. Then, irrespective of problem 1, you can still look at how sensitive the resulting PAF is to various truncation limits. 

I guess I was being a little naive when I said you could trust researchers to pick reasonable truncation limits. I'm by no means an expert on what kinds of assumptions people make across different fields regarding CRA, and I simply assumed there would not be huge discrepancies in truncation limits (Ask me again when I've read the paper you've sent, but right now I think it's pretty reasonable to choose truncation limits based on data in some common sense ways, e.g, should be higher than max observed). From what I've seen, there is little thought put into distribution assumptions (often times normality is assumed, but not actually reported) with any of kind of "truncation" being done for purely practical computational reasons (in our case, we use upperbound of six standard deviation above of the mean, hopefully enough that we should get near 1 PAFs when using problematic non-converging distributions). 

If you think truncation is a real danger though, then certainly you should emphasize it. 
Potentially, we disagree on a philosophical level whether to place the blame on a faulty CRA analysis using distributional assumptions on the method itself or the researchers that made faulty assumptions (I would blame the researchers, the method is fine if used responsibly). 

To go back to the hypothetical example you created earlier where Researcher 1 truncates at 40 and researcher 2 truncates at 110, I would suggest that the resulting PAF (assuming the "true" untruncated PAF isn't 1, so not log normal) should be not extremely different. If not, most likely there are observations over 40, in which case researcher 1 is out of line for choosing a limit below max observed.

**Comment by RodrigoZepeda** [comment]
> But this seems more like an illustration of why problem 1 is an issue that cannot be "solved" by truncation, not it's own problem.

I agree too. The truncation "problem" is not a problem by itself (if correctly done) but the same problem as problem 3: distribution choosing. It seems to me (and what I gather from your discussion seems to back it up) that most times there is no statistics rationale for the truncation limit. Say why 6 standard deviations and not 7 sd's or pi*sd? The same happens with choosing maxima and minima from the data: why not 1.24*maxima? 

> I would blame the researchers

Me too.

>  I would suggest that the resulting PAF (assuming the "true" untruncated PAF isn't 1, so not log normal) should be not extremely different.

Ok! We are working in a new one and adding a plot for illustration purposes.

**Comment by RodrigoZepeda** [comment]
**Additional gamma thoughts**

1. _Truncating convergent gammas_

> Might be more interesting/helpful to look at gamma distributions that don't diverge and see how sensitive they are truncation

Assume using the complete gamma results in a PAF of `Y` then by the same assumptions used in the proof (that relative risk is increasing function of the exposure such as an exponential or linear rr) you can get a PAF of any value on the interval `(0, Y)`. (The proof is the same except for the last paragraph in which `1` is changed to `Y`)

2. _Why I don't recommend gammas_

In theoretical discussions there is no problem assuming a gamma. However in real life, and assuming the gamma converges, researchers won't know the "real" gamma and only have estimators. Here lies the problem. For any parameters `alpha` and `beta` of their "real life gamma" there will always be a **positive probability** that their estimators `alpha_hat` and `beta_hat` result in a distribution that doesn't converge. 

It is also possible to have it the other way around: that the real life parameters (say mean and variance) won't converge if inputed to a gamma but that the estimators result in a convergent gamma. This can also happen with **positive probability**.

**Comment by RodrigoZepeda** [comment]
I have overcomplicated the proof in my previous comment. It is simpler to see it by an application of the [intermediate value theorem](https://en.wikipedia.org/wiki/Intermediate_value_theorem) from Calculus as the PAF is continuous as a function of the truncation limit.
