### ISSUE TITLE
On Approximate empirical method

### ISSUE THREAD

**Issue by fcudhea** [INSP-RH/pifpaf#8]
Quick question on blue text: Can this be right? If sigma^2 is near 0, wouldn't sigma_hat^2 also be near 0 and then the second term in the denominator wouldn't be necessary?

**Comment by RodrigoZepeda** [comment]
With a certain probability yup. Remember that sigma_hat^2  is a random variable and that if you are very unlucky sigma_hat^2 might be large (you should do some hypothesis testing on that). 

> then the second term in the denominator wouldn't be necessary?

It usually isn't but it's nice to have it (just in case)  don't you think?

**Comment by RodrigoZepeda** [comment]
Hey Fred!

Sorry for our delay; we'll start answering your inquiries ASAP.  Before addressing the issue I just want to correct an errata: **it is not that sigma^2 is near 0 but that `(X - µ)^3 ` is near 0.** This `(X - µ)^3 `arises from the error term in the Taylor expansion. 

> But if the method only works when E[(X - µ)^3] is near 0, how useful is it?

Certainly not very useful if your distribution is heavy tailed (say income or genetics) and that's why finance specialists or geneticists don't usually use the delta method (however, in that case, a normality assumption wouldn't be a good one either*).  This is a strong hypothesis as you say but I think it is milder than assuming any distribution (for the argument's sake  Normality) in which some of the assumptions are:

1. Unique Mode = Median = Mean 
2. Distribution is continuous
3. Symmetry => skewness = 0 => E[(X - µ)^3] = 0. _(notice that assuming a distribution automatically makes assumptions on skewness which is what we are doing too)_
4. All real numbers are possible values

An additional advantage is that you can always extend the method to include more information (if `n` sample-moments are known then we can achieve an `n` order approximation in which `E[(X - µ)^(n+1)]` is assumed to be close to 0 and _this is I believe a very good hypothesis for our case. I encourage you to try it both with real life and simulated data to see that as n increases the expected value goes to 0_). See the comment below for a fragment of our draft explaining this expansion. 

I think the best way to explain this (without the probabilistic mumbo-jumbo) is that if your exposure is likely to result in values that are well approximated by the Relative Risk's Taylor expansion you'll be fine. 

*Try `mean(rnorm(1000, 10, 20) - 10)^3` in R several times to see that the normal also results close to 0 at least empirically.

**Comment by RodrigoZepeda** [comment]
<img width="909" alt="captura de pantalla 2017-01-11 a la s 5 45 17 p m" src="https://cloud.githubusercontent.com/assets/13838319/21872084/0f3f55f6-d82c-11e6-8407-eb5f399cdde5.png">

**Comment by RodrigoZepeda** [comment]
Hey Fred, 

Could we move our discussion to [this other repository](https://github.com/INSP-RH/SSB_PAF/issues/1) where we will be analyzing the  PAF of mortality attributable to SSB in Mexico (similar to what you did with Gita worldwide)?
